### ISSUE TITLE
Show actual status of firewall

### ISSUE THREAD

**Issue by lkiesow** [UOS-RZ/deterrers#58] opened 2024-09-17 13:24 UTC
We have seen several times that DETERRERS returns the status `Obline` for a given host while the rule has not actually made its way to the actual firewall. This may be due to a sync delay, or because something just broke somewhere. This missing feedback makes it really troublesome to debug issues and determine the actual state.

**Comment by nwintering** [comment] 2024-10-31 15:01
Duplicate of #36

**Closed by nwintering** 2024-10-31 15:01 UTC
Labels: status:duplicate
