### ISSUE TITLE
DETERRERS state does not seem to represent the firewall state

### ISSUE THREAD

**Issue by lkiesow** [UOS-RZ/deterrers#43] opened 2023-11-30 11:26 UTC
The status listed in DETERRERS does not always seem to map to the actual state of the firewall. That's a real problem since you literally cannot figure out which firewall rules apply for a given host. You only can try a best-effort approach by probing the ports.

To reproduce the issue, register a host, skipping the security scan:
```
❯ deterrerscli action register --skip-scan some-domain.de                                                         
```

Then check the state of the host. It should be listed as online:
```
❯ deterrerscli get some-domain.de | jq .status
"Online"
```

However, trying to access the IP address, it seems like to firewall rules have not been applied.

**Comment by nwintering** [comment] 2024-04-19 12:05
duplicate of #36

**Closed by nwintering** 2024-04-19 12:05 UTC
Labels: type:bug
